import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const operators = [
    { id: "aak", name: "Aak", class: "specialist", rarity: 6, tier: "S", img: "char_225_haak" },
    { id: "angelina", name: "Angelina", class: "supporter", rarity: 6, tier: "S", img: "char_291_aglina" },
    { id: "archetto", name: "Archetto", class: "sniper", rarity: 6, tier: "S", img: "char_332_archet" },
    { id: "ash", name: "Ash", class: "sniper", rarity: 6, tier: "S", img: "char_456_ash" },
    { id: "bagpipe", name: "Bagpipe", class: "vanguard", rarity: 6, tier: "S", img: "char_222_bpipe" },
    { id: "blaze", name: "Blaze", class: "guard", rarity: 6, tier: "S", img: "char_017_huang" },
    { id: "blemishine", name: "Blemishine", class: "defender", rarity: 6, tier: "S", img: "char_423_blemsh" },
    { id: "carnelian", name: "Carnelian", class: "caster", rarity: 6, tier: "S", img: "char_426_billro" },
    { id: "ceobe", name: "Ceobe", class: "caster", rarity: 6, tier: "S", img: "char_2013_cerber" },
    { id: "ch'en", name: "Ch'en", class: "guard", rarity: 6, tier: "S", img: "char_010_chen" },
    { id: "ch'en the holungday", name: "Ch'en the Holungday", class: "sniper", rarity: 6, tier: "S", img: "char_1013_chen2" },
    { id: "chongyue", name: "Chongyue", class: "guard", rarity: 6, tier: "S", img: "char_2024_chyue" },
    { id: "civilight eterna", name: "Civilight Eterna", class: "supporter", rarity: 6, tier: "S", img: "char_4134_cetsyr" },
    { id: "degenbrecher", name: "Degenbrecher", class: "guard", rarity: 6, tier: "S", img: "char_4116_blkkgt" },
    { id: "dorothy", name: "Dorothy", class: "specialist", rarity: 6, tier: "S", img: "char_4048_doroth" },
    { id: "dusk", name: "Dusk", class: "caster", rarity: 6, tier: "S", img: "char_2015_dusk" },
    { id: "ebenholz", name: "Ebenholz", class: "caster", rarity: 6, tier: "S", img: "char_4046_ebnhlz" },
    { id: "ela", name: "Ela", class: "specialist", rarity: 6, tier: "S", img: "char_4123_ela" },
    { id: "eunectes", name: "Eunectes", class: "defender", rarity: 6, tier: "S", img: "char_416_zumama" },
    { id: "executor the ex foedere", name: "Executor the Ex Foedere", class: "guard", rarity: 6, tier: "S", img: "char_1032_excu2" },
    { id: "exusiai", name: "Exusiai", class: "sniper", rarity: 6, tier: "S", img: "char_1032_excu2" },
    { id: "eyjafjalla", name: "Eyjafjalla", class: "caster", rarity: 6, tier: "S", img: "char_180_amgoat" },
    { id: "eyjafjalla the hvít aska", name: "Eyjafjalla the Hvít Aska", class: "medic", rarity: 6, tier: "S", img: "char_1016_agoat2" },
    { id: "fartooth", name: "Fartooth", class: "sniper", rarity: 6, tier: "S", img: "char_430_fartth" },
    { id: "fiammetta", name: "Fiammetta", class: "sniper", rarity: 6, tier: "S", img: "char_300_phenxi" },
    { id: "flametail", name: "Flametail", class: "vanguard", rarity: 6, tier: "S", img: "char_420_flamtl" },
    { id: "gavial the invincible", name: "Gavial the Invincible", class: "guard", rarity: 6, tier: "S", img: "char_1026_gvial2" },
    { id: "gladiia", name: "Gladiia", class: "specialist", rarity: 6, tier: "S", img: "char_474_glady" },
    { id: "gnosis", name: "Gnosis", class: "supporter", rarity: 6, tier: "S", img: "char_206_gnosis" },
    { id: "goldenglow", name: "Goldenglow", class: "caster", rarity: 6, tier: "S", img: "char_377_gdglow" },
    { id: "hellagur", name: "Hellagur", class: "guard", rarity: 6, tier: "S", img: "char_188_helage" },
    { id: "ho'olheyak", name: "Ho'olheyak", class: "caster", rarity: 6, tier: "S", img: "char_4027_heyak" },
    { id: "hoederer", name: "Hoederer", class: "guard", rarity: 6, tier: "S", img: "char_4088_hodrer" },
    { id: "horn", name: "Horn", class: "defender", rarity: 6, tier: "S", img: "char_4039_horn" },
    { id: "hoshiguma", name: "Hoshiguma", class: "defender", rarity: 6, tier: "S", img: "char_136_hsguma" },
    { id: "ifrit", name: "Ifrit", class: "caster", rarity: 6, tier: "S", img: "char_134_ifrit" },
    { id: "ines", name: "Ines", class: "vanguard", rarity: 6, tier: "S", img: "char_4087_ines" },
    { id: "irene", name: "Irene", class: "guard", rarity: 6, tier: "S", img: "char_4009_irene" },
    { id: "jessica the liberated", name: "Jessica the Liberated", class: "defender", rarity: 6, tier: "S", img: "char_1034_jesca2" },
    { id: "kal'tsit", name: "Kal'tsit", class: "medic", rarity: 6, tier: "S", img: "char_003_kalts" },
    { id: "kirin r yato", name: "Kirin R Yato", class: "specialist", rarity: 6, tier: "S", img: "char_1029_yato2" },
    { id: "lee", name: "Lee", class: "specialist", rarity: 6, tier: "S", img: "char_322_lmlee" },
    { id: "lessing", name: "Lessing", class: "guard", rarity: 6, tier: "S", img: "char_4011_lessng" },
    { id: "lin", name: "Lin", class: "caster", rarity: 6, tier: "S", img: "char_4080_lin" },
    { id: "ling", name: "Ling", class: "supporter", rarity: 6, tier: "S", img: "char_2023_ling" },
    { id: "logos", name: "Logos", class: "caster", rarity: 6, tier: "S", img: "char_4133_logos" },
    { id: "lumen", name: "Lumen", class: "medic", rarity: 6, tier: "S", img: "char_4042_lumen" },
    { id: "magallan", name: "Magallan", class: "supporter", rarity: 6, tier: "S", img: "char_248_mgllan" },
    { id: "mizuki", name: "Mizuki", class: "specialist", rarity: 6, tier: "S", img: "char_437_mizuki" },
    { id: "mostima", name: "Mostima", class: "caster", rarity: 6, tier: "S", img: "char_213_mostma" },
    { id: "mountain", name: "Mountain", class: "guard", rarity: 6, tier: "S", img: "char_264_f12yin" },
    { id: "mudrock", name: "Mudrock", class: "defender", rarity: 6, tier: "S", img: "char_311_mudrok" },
    { id: "muelsyse", name: "Muelsyse", class: "vanguard", rarity: 6, tier: "S", img: "char_249_mlyss" },
    { id: "młynar", name: "Młynar", class: "guard", rarity: 6, tier: "S", img: "char_4064_mlynar" },
    { id: "narantuya", name: "Narantuya", class: "sniper", rarity: 6, tier: "S", img: "char_4138_narant" },
    { id: "nearl the radiant knight", name: "Nearl the Radiant Knight", class: "guard", rarity: 6, tier: "S", img: "char_1014_nearl2" },
    { id: "nian", name: "Nian", class: "defender", rarity: 6, tier: "S", img: "char_2014_nian" },
    { id: "nightingale", name: "Nightingale", class: "medic", rarity: 6, tier: "S", img: "char_179_cgbird" },
    { id: "pallas", name: "Pallas", class: "guard", rarity: 6, tier: "S", img: "char_485_pallas" },
    { id: "passenger", name: "Passenger", class: "caster", rarity: 6, tier: "S", img: "char_472_pasngr" },
    { id: "penance", name: "Penance", class: "defender", rarity: 6, tier: "S", img: "char_4065_judge" },
    { id: "pepe", name: "Pepe", class: "guard", rarity: 6, tier: "S", img: "char_4058_pepe" },
    { id: "phantom", name: "Phantom", class: "specialist", rarity: 6, tier: "S", img: "char_250_phatom" },
    { id: "pozëmka", name: "Pozëmka", class: "sniper", rarity: 6, tier: "S", img: "char_4055_bgsnow" },
    { id: "qiubai", name: "Qiubai", class: "guard", rarity: 6, tier: "S", img: "char_4082_qiubai" },
    { id: "ray", name: "Ray", class: "sniper", rarity: 6, tier: "S", img: "char_4117_ray" },
    { id: "reed the flame shadow", name: "Reed the Flame Shadow", class: "medic", rarity: 6, tier: "S", img: "char_1020_reed2" },
    { id: "rosa", name: "Rosa", class: "sniper", rarity: 6, tier: "S", img: "char_197_poca" },
    { id: "rosmontis", name: "Rosmontis", class: "sniper", rarity: 6, tier: "S", img: "char_391_rosmon" },
    { id: "saga", name: "Saga", class: "vanguard", rarity: 6, tier: "S", img: "char_362_saga" },
    { id: "saileach", name: "Saileach", class: "vanguard", rarity: 6, tier: "S", img: "char_479_sleach" },
    { id: "saria", name: "Saria", class: "defender", rarity: 6, tier: "S", img: "char_202_demkni" },
    { id: "schwarz", name: "Schwarz", class: "sniper", rarity: 6, tier: "S", img: "char_340_shwaz" },
    { id: "shining", name: "Shining", class: "medic", rarity: 6, tier: "S", img: "char_147_shining" },
    { id: "shu", name: "Shu", class: "defender", rarity: 6, tier: "S", img: "char_2025_shu" },
    { id: "siege", name: "Siege", class: "vanguard", rarity: 6, tier: "S", img: "char_112_siege" },
    { id: "silence the paradigmatic", name: "Silence the Paradigmatic", class: "supporter", rarity: 6, tier: "S", img: "char_1031_slent2" },
    { id: "silverash", name: "SilverAsh", class: "guard", rarity: 6, tier: "S", img: "char_172_svrash" },
    { id: "skadi", name: "Skadi", class: "guard", rarity: 6, tier: "S", img: "char_263_skadi" },
    { id: "skadi the corrupting heart", name: "Skadi the Corrupting Heart", class: "supporter", rarity: 6, tier: "S", img: "char_1012_skadi2_iteration#2" },
    { id: "specter the unchained", name: "Specter the Unchained", class: "specialist", rarity: 6, tier: "S", img: "char_1023_ghost2" },
    { id: "stainless", name: "Stainless", class: "supporter", rarity: 6, tier: "S", img: "char_4072_ironmn" },
    { id: "surtr", name: "Surtr", class: "guard", rarity: 6, tier: "S", img: "char_350_surtr" },
    { id: "suzuran", name: "Suzuran", class: "supporter", rarity: 6, tier: "S", img: "char_358_lisa" },
    { id: "swire the elegant wit", name: "Swire the Elegant Wit", class: "specialist", rarity: 6, tier: "S", img: "char_1033_swire2" },
    { id: "texas the omertosa", name: "Texas the Omertosa", class: "specialist", rarity: 6, tier: "S", img: "char_1028_texas2_iteration#1" },
    { id: "thorns", name: "Thorns", class: "guard", rarity: 6, tier: "S", img: "char_293_thorns" },
    { id: "typhon", name: "Typhon", class: "sniper", rarity: 6, tier: "S", img: "char_2012_typhon" },
    { id: "ulpianus", name: "Ulpianus", class: "guard", rarity: 6, tier: "S", img: "char_4145_ulpia" },
    { id: "vigil", name: "Vigil", class: "vanguard", rarity: 6, tier: "S", img: "char_427_vigil" },
    { id: "virtuosa", name: "Virtuosa", class: "vanguard", rarity: 6, tier: "S", img: "char_245_cello" },
    { id: "viviana", name: "Viviana", class: "vanguard", rarity: 6, tier: "S", img: "char_4098_vvana" },
    { id: "w", name: "W", class: "sniper", rarity: 6, tier: "S", img: "char_113_cqbw" },
    { id: "weedy", name: "Weedy", class: "specialist", rarity: 6, tier: "S", img: "char_400_weedy" },
    { id: "wiš'adel", name: "Wiš'adel", class: "sniper", rarity: 6, tier: "S", img: "char_1035_wisdel" },
    { id: "zuo le", name: "Zuo Le", class: "guard", rarity: 6, tier: "S", img: "char_4121_zuole" },
    { id: "absinthe", name: "Absinthe", class: "caster", rarity: 5, tier: "S", img: "char_405_absin" },
    { id: "akafuyu", name: "Akafuyu", class: "guard", rarity: 5, tier: "S", img: "char_475_akafyu" },
    { id: "almond", name: "Almond", class: "specialist", rarity: 5, tier: "S", img: "char_4105_almond" },
    { id: "amiya", name: "Amiya", class: "caster", rarity: 5, tier: "S", img: "char_002_amiya" },
    { id: "amiya (medic)", name: "Amiya (Medic)", class: "medic", rarity: 5, tier: "S", img: "char_002_amiya" },
    { id: "andreana", name: "Andreana", class: "sniper", rarity: 5, tier: "S", img: "char_218_cuttle" },
    { id: "aosta", name: "Aosta", class: "sniper", rarity: 5, tier: "S", img: "char_346_aosta" },
    { id: "april", name: "April", class: "sniper", rarity: 5, tier: "S", img: "char_365_aprl" },
    { id: "aroma", name: "Aroma", class: "caster", rarity: 5, tier: "S", img: "char_446_aroma" },
    { id: "asbestos", name: "Asbestos", class: "defender", rarity: 5, tier: "S", img: "char_378_asbest" },
    { id: "ashlock", name: "Ashlock", class: "defender", rarity: 5, tier: "S", img: "char_431_ashlok" },
    { id: "astesia", name: "Astesia", class: "guard", rarity: 5, tier: "S", img: "char_274_astesi" },
    { id: "astgenne", name: "Astgenne", class: "caster", rarity: 5, tier: "S", img: "char_135_halo" },
    { id: "aurora", name: "Aurora", class: "defender", rarity: 5, tier: "S", img: "char_422_aurora" },
    { id: "ayerscarpe", name: "Ayerscarpe", class: "guard", rarity: 5, tier: "S", img: "char_294_ayer" },
    { id: "bassline", name: "Bassline", class: "defender", rarity: 5, tier: "S", img: "char_4109_baslin" },
    { id: "beeswax", name: "Beeswax", class: "caster", rarity: 5, tier: "S", img: "char_344_beewax" },
    { id: "bena", name: "Bena", class: "specialist", rarity: 5, tier: "S", img: "char_369_bena" },
    { id: "bibeak", name: "Bibeak", class: "guard", rarity: 5, tier: "S", img: "char_252_bibeak" },
    { id: "bison", name: "Bison", class: "defender", rarity: 5, tier: "S", img: "char_325_bison" },
    { id: "blacknight", name: "Blacknight", class: "vanguard", rarity: 5, tier: "S", img: "char_476_blkngt" },
    { id: "blitz", name: "Blitz", class: "defender", rarity: 5, tier: "S", img: "char_457_blitz" },
    { id: "blue poison", name: "Blue Poison", class: "sniper", rarity: 5, tier: "S", img: "char_129_bluep" },
    { id: "breeze", name: "Breeze", class: "medic", rarity: 5, tier: "S", img: "char_275_breeze" },
    { id: "broca", name: "Broca", class: "guard", rarity: 5, tier: "S", img: "char_356_broca" },
    { id: "bryophyta", name: "Bryophyta", class: "guard", rarity: 5, tier: "S", img: "Bryophyta_icon" },
    { id: "cantabile", name: "Cantabile", class: "vanguard", rarity: 5, tier: "S", img: "char_497_ctable" },
    { id: "cement", name: "Cement", class: "defender", rarity: 5, tier: "S", img: "char_464_cement" },
    { id: "ceylon", name: "Ceylon", class: "medic", rarity: 5, tier: "S", img: "char_348_ceylon" },
    { id: "chiave", name: "Chiave", class: "vanguard", rarity: 5, tier: "S", img: "char_349_chiave" },
    { id: "cliffheart", name: "Cliffheart", class: "specialist", rarity: 5, tier: "S", img: "char_173_slchan" },
    { id: "coldshot", name: "Coldshot", class: "sniper", rarity: 5, tier: "S", img: "char_4104_coldst" },
    { id: "corroserum", name: "Corroserum", class: "caster", rarity: 5, tier: "S", img: "char_489_serum" },
    { id: "croissant", name: "Croissant", class: "defender", rarity: 5, tier: "S", img: "char_201_moeshd" },
    { id: "czerny", name: "Czerny", class: "defender", rarity: 5, tier: "S", img: "char_4047_pianst" },
    { id: "dagda", name: "Dagda", class: "guard", rarity: 5, tier: "S", img: "char_157_dagda" },
    { id: "delphine", name: "Delphine", class: "caster", rarity: 5, tier: "S", img: "char_4110_delphn" },
    { id: "diamante", name: "Diamante", class: "caster", rarity: 5, tier: "S", img: "char_499_kaitou" },
    { id: "doc", name: "Doc", class: "defender", rarity: 5, tier: "S", img: "char_4125_rdoc" },
    { id: "elysium", name: "Elysium", class: "vanguard", rarity: 5, tier: "S", img: "char_401_elysm" },
    { id: "enforcer", name: "Enforcer", class: "specialist", rarity: 5, tier: "S", img: "char_4036_forcer" },
    { id: "erato", name: "Erato", class: "sniper", rarity: 5, tier: "S", img: "char_4043_erato" },
    { id: "executor", name: "Executor", class: "sniper", rarity: 5, tier: "S", img: "char_279_excu" },
    { id: "feater", name: "FEater", class: "specialist", rarity: 5, tier: "S", img: "char_241_panda" },
    { id: "fang the fire-sharpened", name: "Fang the Fire-Sharpened", class: "vanguard", rarity: 5, tier: "S", img: "char_1036_fang2" },
    { id: "firewatch", name: "Firewatch", class: "sniper", rarity: 5, tier: "S", img: "" },
    { id: "firewhistle", name: "Firewhistle", class: "defender", rarity: 5, tier: "S", img: "char_493_firwhl" },
    { id: "flamebringer", name: "Flamebringer", class: "guard", rarity: 5, tier: "S", img: "char_131_flameb" },
    { id: "flint", name: "Flint", class: "guard", rarity: 5, tier: "S", img: "char_158_milu" },
    { id: "folinic", name: "Folinic", class: "medic", rarity: 5, tier: "S", img: "char_345_folnic" },
    { id: "franka", name: "Franka", class: "guard", rarity: 5, tier: "S", img: "char_106_franka" },
    { id: "frost", name: "Frost", class: "specialist", rarity: 5, tier: "S", img: "Frost-icon" },
    { id: "fuze", name: "Fuze", class: "specialist", rarity: 5, tier: "S", img: "char_4126_fuze" },
    { id: "glaucus", name: "Glaucus", class: "supporter", rarity: 5, tier: "S", img: "char_326_glacus" },
    { id: "grain buds", name: "Grain Buds", class: "supporter", rarity: 5, tier: "S", img: "char_4122_grabds" },
    { id: "grani", name: "Grani", class: "vanguard", rarity: 5, tier: "S", img: "char_220_grani" },
    { id: "greythroat", name: "GreyThroat", class: "sniper", rarity: 5, tier: "S", img: "char_367_swllow" },
    { id: "greyy the lightningbearer", name: "Greyy the Lightningbearer", class: "sniper", rarity: 5, tier: "S", img: "char_1027_greyy2" },
    { id: "harmonie", name: "Harmonie", class: "caster", rarity: 5, tier: "S", img: "char_297_hamoni" },
    { id: "harold", name: "Harold", class: "medic", rarity: 5, tier: "S", img: "char_4114_harold" },
    { id: "heavyrain", name: "Heavyrain", class: "defender", rarity: 5, tier: "S", img: "char_304_zebra" },
    { id: "heidi", name: "Heidi", class: "supporter", rarity: 5, tier: "S", img: "char_4045_heidi" },
    { id: "hibiscus the purifier", name: "Hibiscus the Purifier", class: "medic", rarity: 5, tier: "S", img: "char_1024_hbisc2" },
    { id: "highmore", name: "Highmore", class: "guard", rarity: 5, tier: "S", img: "char_4066_highmo" },
    { id: "honeyberry", name: "Honeyberry", class: "medic", rarity: 5, tier: "S", img: "char_449_glider" },
    { id: "hung", name: "Hung", class: "defender", rarity: 5, tier: "S", img: "char_226_hmau" },
    { id: "iana", name: "Iana", class: "specialist", rarity: 5, tier: "S", img: "char_4124_iana" },
    { id: "indra", name: "Indra", class: "guard", rarity: 5, tier: "S", img: "char_155_tiger" },
    { id: "insider", name: "Insider", class: "sniper", rarity: 5, tier: "S", img: "char_498_inside" },
    { id: "iris", name: "Iris", class: "caster", rarity: 5, tier: "S", img: "char_338_iris" },
    { id: "istina", name: "Istina", class: "supporter", rarity: 5, tier: "S", img: "char_195_glassb" },
    { id: "jieyun", name: "Jieyun", class: "sniper", rarity: 5, tier: "S", img: "char_4078_bdhkgt" },
    { id: "kafka", name: "Kafka", class: "specialist", rarity: 5, tier: "S", img: "char_214_kafka" },
    { id: "kazemaru", name: "Kazemaru", class: "specialist", rarity: 5, tier: "S", img: "char_4016_kazema" },
    { id: "kestrel", name: "Kestrel", class: "vanguard", rarity: 5, tier: "S", img: "Kestrel-icon" },
    { id: "kirara", name: "Kirara", class: "specialist", rarity: 5, tier: "S", img: "char_478_kirara" },
    { id: "kjera", name: "Kjera", class: "caster", rarity: 5, tier: "S", img: "char_4013_kjera" },
    { id: "kroos the keen glint", name: "Kroos the Keen Glint", class: "sniper", rarity: 5, tier: "S", img: "char_1021_kroos2" },
    { id: "la pluma", name: "La Pluma", class: "guard", rarity: 5, tier: "S", img: "char_421_crow" },
    { id: "lappland", name: "Lappland", class: "guard", rarity: 5, tier: "S", img: "char_140_whitew" },
    { id: "lava the purgatory", name: "Lava the Purgatory", class: "caster", rarity: 5, tier: "S", img: "char_1011_lava2" },
    { id: "leizi", name: "Leizi", class: "caster", rarity: 5, tier: "S", img: "char_306_leizi" },
    { id: "leonhardt", name: "Leonhardt", class: "caster", rarity: 5, tier: "S", img: "char_373_lionhd" },
    { id: "leto", name: "Leto", class: "guard", rarity: 5, tier: "S", img: "char_194_leto" },
    { id: "liskarm", name: "Liskarm", class: "defender", rarity: 5, tier: "S", img: "char_107_liskam" },
    { id: "lucilla", name: "Lucilla", class: "supporter", rarity: 5, tier: "S", img: "Lucilla-icon" },
    { id: "lunacub", name: "Lunacub", class: "sniper", rarity: 5, tier: "S", img: "char_4014_lunacu" },
    { id: "manticore", name: "Manticore", class: "specialist", rarity: 5, tier: "S", img: "char_215_mantic" },
    { id: "mayer", name: "Mayer", class: "supporter", rarity: 5, tier: "S", img: "char_242_otter" },
    { id: "melanite", name: "Melanite", class: "sniper", rarity: 5, tier: "S", img: "char_4006_melnte" },
    { id: "meteorite", name: "Meteorite", class: "sniper", rarity: 5, tier: "S", img: "char_219_meteo" },
    { id: "minimalist", name: "Minimalist", class: "caster", rarity: 5, tier: "S", img: "char_4054_malist" },
    { id: "mint", name: "Mint", class: "caster", rarity: 5, tier: "S", img: "char_388_mint" },
    { id: "morgan", name: "Morgan", class: "guard", rarity: 5, tier: "S", img: "char_154_morgan" },
    { id: "mr. nothing", name: "Mr. Nothing", class: "specialist", rarity: 5, tier: "S", img: "char_455_nothin" },
    { id: "mulberry", name: "Mulberry", class: "medic", rarity: 5, tier: "S", img: "char_473_mberry" },
    { id: "nearl", name: "Nearl", class: "defender", rarity: 5, tier: "S", img: "char_148_nearl" },
    { id: "nightmare", name: "Nightmare", class: "caster", rarity: 5, tier: "S", img: "char_164_nightm" },
    { id: "nine-colored deer", name: "Nine-Colored Deer", class: "supporter", rarity: 5, tier: "S", img: "char_4019_ncdeer" },
    { id: "odda", name: "Odda", class: "guard", rarity: 5, tier: "S", img: "char_4131_odda" },
    { id: "paprika", name: "Paprika", class: "medic", rarity: 5, tier: "S", img: "char_4071_peper" },
    { id: "papyrus", name: "Papyrus", class: "medic", rarity: 5, tier: "S", img: "char_4139_papyrs" },
    { id: "platinum", name: "Platinum", class: "sniper", rarity: 5, tier: "S", img: "char_204_platnm" },
    { id: "poncirus", name: "Poncirus", class: "vanguard", rarity: 5, tier: "S", img: "char_488_buildr" },
    { id: "pramanix", name: "Pramanix", class: "supporter", rarity: 5, tier: "S", img: "char_174_slbell" },
    { id: "projekt red", name: "Projekt Red", class: "specialist", rarity: 5, tier: "S", img: "char_144_red" },
    { id: "provence", name: "Provence", class: "sniper", rarity: 5, tier: "S", img: "char_145_prove" },
    { id: "proviso", name: "Proviso", class: "supporter", rarity: 5, tier: "S", img: "char_4032_provs" },
    { id: "ptilopsis", name: "Ptilopsis", class: "medic", rarity: 5, tier: "S", img: "char_128_plosis" },
    { id: "puzzle", name: "Puzzle", class: "vanguard", rarity: 5, tier: "S", img: "char_4017_puzzle" },
    { id: "qanipalaat", name: "Qanipalaat", class: "caster", rarity: 5, tier: "S", img: "char_466_qanik" },
    { id: "quercus", name: "Quercus", class: "supporter", rarity: 5, tier: "S", img: "char_492_quercu" },
    { id: "rathalos s noir corne", name: "Rathalos S Noir Corne", class: "guard", rarity: 5, tier: "S", img: "char_1030_noirc2" },
    { id: "reed", name: "Reed", class: "vanguard", rarity: 5, tier: "S", img: "char_261_sddrag" },
    { id: "robin", name: "Robin", class: "specialist", rarity: 5, tier: "S", img: "char_451_robin" },
    { id: "rockrock", name: "Rockrock", class: "caster", rarity: 5, tier: "S", img: "char_4040_rockr" },
    { id: "sand reckoner", name: "Sand Reckoner", class: "supporter", rarity: 5, tier: "S", img: "char_4140_lasher" },
    { id: "santalla", name: "Santalla", class: "caster", rarity: 5, tier: "S", img: "char_341_sntlla" },
    { id: "savage", name: "Savage", class: "guard", rarity: 5, tier: "S", img: "char_230_savage" },
    { id: "scene", name: "Scene", class: "supporter", rarity: 5, tier: "S", img: "char_336_folivo" },
    { id: "sesa", name: "Sesa", class: "sniper", rarity: 5, tier: "S", img: "char_379_sesa" },
    { id: "shalem", name: "Shalem", class: "defender", rarity: 5, tier: "S", img: "char_512_aprot" },
    { id: "shamare", name: "Shamare", class: "supporter", rarity: 5, tier: "S", img: "char_254_vodfox" },
    { id: "sideroca", name: "Sideroca", class: "guard", rarity: 5, tier: "S", img: "char_333_sidero" },
    { id: "silence", name: "Silence", class: "medic", rarity: 5, tier: "S", img: "char_108_silent" },
    { id: "skyfire", name: "Skyfire", class: "caster", rarity: 5, tier: "S", img: "char_166_skfire" },
    { id: "snowsant", name: "Snowsant", class: "specialist", rarity: 5, tier: "S", img: "char_383_snsant" },
    { id: "sora", name: "Sora", class: "supporter", rarity: 5, tier: "S", img: "char_101_sora" },
    { id: "specter", name: "Specter", class: "guard", rarity: 5, tier: "S", img: "char_143_ghost" },
    { id: "spuria", name: "Spuria", class: "specialist", rarity: 5, tier: "S", img: "char_4015_spuria" },
    { id: "swire", name: "Swire", class: "guard", rarity: 5, tier: "S", img: "char_308_swire" },
    { id: "tachanka", name: "Tachanka", class: "guard", rarity: 5, tier: "S", img: "char_459_tachak" },
    { id: "tequila", name: "Tequila", class: "guard", rarity: 5, tier: "S", img: "char_486_takila" },
    { id: "texas", name: "Texas", class: "vanguard", rarity: 5, tier: "S", img: "char_102_texas" },
    { id: "toddifons", name: "Toddifons", class: "sniper", rarity: 5, tier: "S", img: "char_363_toddi" },
    { id: "tomimi", name: "Tomimi", class: "caster", rarity: 5, tier: "S", img: "char_411_tomimi" },
    { id: "tsukinogi", name: "Tsukinogi", class: "supporter", rarity: 5, tier: "S", img: "char_343_tknogi" },
    { id: "tuye", name: "Tuye", class: "medic", rarity: 5, tier: "S", img: "char_402_tuye" },
    { id: "underflow", name: "Underflow", class: "defender", rarity: 5, tier: "S", img: "char_4137_udflow" },
    { id: "valarqvin", name: "Valarqvin", class: "supporter", rarity: 5, tier: "S", img: "Valarqvin-icon" },
    { id: "vendela", name: "Vendela", class: "medic", rarity: 5, tier: "S", img: "char_494_vendla" },
    { id: "vulcan", name: "Vulcan", class: "defender", rarity: 5, tier: "S", img: "char_163_hpsts" },
    { id: "waai fu", name: "Waai Fu", class: "specialist", rarity: 5, tier: "S", img: "char_243_waaifu" },
    { id: "wanqing", name: "Wanqing", class: "vanguard", rarity: 5, tier: "S", img: "char_4119_wanqin" },
    { id: "warfarin", name: "Warfarin", class: "medic", rarity: 5, tier: "S", img: "char_171_bldsk" },
    { id: "whislash", name: "Whislash", class: "guard", rarity: 5, tier: "S", img: "char_265_sophia" },
    { id: "whisperain", name: "Whisperain", class: "medic", rarity: 5, tier: "S", img: "char_436_whispr" },
    { id: "wild mane", name: "Wild Mane", class: "vanguard", rarity: 5, tier: "S", img: "char_496_wildmn" },
    { id: "wind chimes", name: "Wind Chimes", class: "guard", rarity: 5, tier: "S", img: "char_4083_chimes" },
    { id: "windflit", name: "Windflit", class: "supporter", rarity: 5, tier: "S", img: "char_433_windft" },
    { id: "zima", name: "Zima", class: "vanguard", rarity: 5, tier: "S", img: "char_115_headbr" },
    { id: "aciddrop", name: "Aciddrop", class: "sniper", rarity: 4, tier: "S", img: "char_366_acdrop" },
    { id: "ambriel", name: "Ambriel", class: "sniper", rarity: 4, tier: "S", img: "char_302_glaze" },
    { id: "arene", name: "Arene", class: "guard", rarity: 4, tier: "S", img: "char_271_spikes" },
    { id: "beanstalk", name: "Beanstalk", class: "vanguard", rarity: 4, tier: "S", img: "char_452_bstalk" },
    { id: "beehunter", name: "Beehunter", class: "guard", rarity: 4, tier: "S", img: "char_137_brownb" },
    { id: "bubble", name: "Bubble", class: "defender", rarity: 4, tier: "S", img: "char_381_bubble" },
    { id: "caper", name: "Caper", class: "sniper", rarity: 4, tier: "S", img: "char_4100_caper" },
    { id: "chestnut", name: "Chestnut", class: "medic", rarity: 4, tier: "S", img: "char_4041_chnut" },
    { id: "click", name: "Click", class: "caster", rarity: 4, tier: "S", img: "char_328_cammou" },
    { id: "conviction", name: "Conviction", class: "guard", rarity: 4, tier: "S", img: "char_159_peacok" },
    { id: "courier", name: "Courier", class: "vanguard", rarity: 4, tier: "S", img: "char_198_blackd" },
    { id: "cuora", name: "Cuora", class: "defender", rarity: 4, tier: "S", img: "char_150_snakek" },
    { id: "cutter", name: "Cutter", class: "guard", rarity: 4, tier: "S", img: "char_301_cutter" },
    { id: "deepcolor", name: "Deepcolor", class: "supporter", rarity: 4, tier: "S", img: "char_110_deepcl" },
    { id: "dobermann", name: "Dobermann", class: "guard", rarity: 4, tier: "S", img: "char_130_doberm" },
    { id: "dur-nar", name: "Dur-nar", class: "defender", rarity: 4, tier: "S", img: "char_260_durnar" },
    { id: "earthspirit", name: "Earthspirit", class: "supporter", rarity: 4, tier: "S", img: "char_183_skgoat" },
    { id: "estelle", name: "Estelle", class: "guard", rarity: 4, tier: "S", img: "char_127_estell" },
    { id: "ethan", name: "Ethan", class: "specialist", rarity: 4, tier: "S", img: "char_355_ethan" },
    { id: "frostleaf", name: "Frostleaf", class: "guard", rarity: 4, tier: "S", img: "char_193_frostl" },
    { id: "gavial", name: "Gavial", class: "medic", rarity: 4, tier: "S", img: "char_187_ccheal" },
    { id: "gitano", name: "Gitano", class: "caster", rarity: 4, tier: "S", img: "char_109_fmout" },
    { id: "gravel", name: "Gravel", class: "specialist", rarity: 4, tier: "S", img: "char_237_gravel" },
    { id: "greyy", name: "Greyy", class: "caster", rarity: 4, tier: "S", img: "char_253_greyy" },
    { id: "gummy", name: "Gummy", class: "defender", rarity: 4, tier: "S", img: "char_196_sunbr" },
    { id: "haze", name: "Haze", class: "caster", rarity: 4, tier: "S", img: "char_141_nights" },
    { id: "humus", name: "Humus", class: "guard", rarity: 4, tier: "S", img: "char_491_humus" },
    { id: "indigo", name: "Indigo", class: "caster", rarity: 4, tier: "S", img: "char_469_indigo" },
    { id: "jackie", name: "Jackie", class: "guard", rarity: 4, tier: "S", img: "char_347_jaksel" },
    { id: "jaye", name: "Jaye", class: "specialist", rarity: 4, tier: "S", img: "char_272_strong" },
    { id: "jessica", name: "Jessica", class: "sniper", rarity: 4, tier: "S", img: "char_235_jesica" },
    { id: "luo xiaohei", name: "Luo Xiaohei", class: "guard", rarity: 4, tier: "S", img: "char_4067_lolxh" },
    { id: "lutonada", name: "Lutonada", class: "defender", rarity: 4, tier: "S", img: "char_4130_luton" },
    { id: "matoimaru", name: "Matoimaru", class: "guard", rarity: 4, tier: "S", img: "char_289_gyuki" },
    { id: "matterhorn", name: "Matterhorn", class: "defender", rarity: 4, tier: "S", img: "char_199_yak" },
    { id: "may", name: "May", class: "sniper", rarity: 4, tier: "S", img: "char_133_mm" },
    { id: "meteor", name: "Meteor", class: "sniper", rarity: 4, tier: "S", img: "char_126_shotst" },
    { id: "mousse", name: "Mousse", class: "guard", rarity: 4, tier: "S", img: "char_185_frncat" },
    { id: "myrrh", name: "Myrrh", class: "medic", rarity: 4, tier: "S", img: "char_117_myrrh" },
    { id: "myrtle", name: "Myrtle", class: "vanguard", rarity: 4, tier: "S", img: "char_151_myrtle" },
    { id: "perfumer", name: "Perfumer", class: "medic", rarity: 4, tier: "S", img: "char_181_flower" },
    { id: "pinecone", name: "Pinecone", class: "sniper", rarity: 4, tier: "S", img: "char_440_pinecn" },
    { id: "podenco", name: "Podenco", class: "supporter", rarity: 4, tier: "S", img: "char_258_podego" },
    { id: "pudding", name: "Pudding", class: "caster", rarity: 4, tier: "S", img: "char_4004_pudd" },
    { id: "purestream", name: "Purestream", class: "medic", rarity: 4, tier: "S", img: "char_385_finlpp" },
    { id: "quartz", name: "Quartz", class: "guard", rarity: 4, tier: "S", img: "char_4063_quartz" },
    { id: "roberta", name: "Roberta", class: "supporter", rarity: 4, tier: "S", img: "char_484_robrta" },
    { id: "rope", name: "Rope", class: "specialist", rarity: 4, tier: "S", img: "char_236_rope" },
    { id: "scavenger", name: "Scavenger", class: "vanguard", rarity: 4, tier: "S", img: "char_149_scave" },
    { id: "shaw", name: "Shaw", class: "specialist", rarity: 4, tier: "S", img: "char_277_sqrrel" },
    { id: "shirayuki", name: "Shirayuki", class: "sniper", rarity: 4, tier: "S", img: "char_118_yuki" },
    { id: "sussurro", name: "Sussurro", class: "medic", rarity: 4, tier: "S", img: "char_298_susuro" },
    { id: "totter", name: "Totter", class: "sniper", rarity: 4, tier: "S", img: "char_4062_totter" },
    { id: "utage", name: "Utage", class: "guard", rarity: 4, tier: "S", img: "char_337_utage" },
    { id: "verdant", name: "Verdant", class: "specialist", rarity: 4, tier: "S", img: "char_4107_vrdant" },
    { id: "vermeil", name: "Vermeil", class: "sniper", rarity: 4, tier: "S", img: "char_190_clour" },
    { id: "vigna", name: "Vigna", class: "vanguard", rarity: 4, tier: "S", img: "char_290_vigna" },
];

async function main() {
  console.log('Seeding database...');

  for (const operator of operators) {
    await prisma.operator.upsert({
      where: { id: operator.id },
      update: operator,
      create: operator,
    });
  }

  console.log('Database seeded!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
